/*****************
 * isLading
*****************/
export const LOADING = {
  IS_LOADING: "IS_LOADING"
}

/****************
      TOKEN
*****************/
export const TOKEN = {
  GET: "GET_TOKEN"
}

export const HEADERS ={
  URL: atob(document.getElementById("hellyeah").value),
  TOKEN:"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwY2RiN2M5OC0wNWNmLTQ4NDgtOGM3Yy0yZTFiYTczZGUwNmYiLCJpYXQiOjE1NzAxNzM0ODYsImV4cCI6MTU3MDc3ODI4Nn0.1NiWtt2luG83am8FJSvWpL5p35Oxd8GSJJTwhFmAdgw",
  USERNAME: "netindo",
  PASSWORD: "$2b$08$hLMU6rEvNILCMaQbthARK.iCmDRO7jNbUB8CcvyRStqsHD4UQxjDO"
}

/****************
      PASSWORD MODAL ADD LOCATION
*****************/
export const LOC_VERIF ={
  password: "bmV0aW4xMjM0YSE="
}

/****************
      MODAL
*****************/
export const MODALS = {
  IS_MODAL_OPEN: 'IS_MODAL_OPEN',
  MODAL_TYPE : 'MODAL_TYPE'
}

/****************
      AUTH
*****************/
export const AUTH = {
  FETCH_DATAS:'FETCH_DATAS',
  GET_ERRORS:'GET_ERRORS',
  TEST_DISPATCH:'TEST_DISPATCH',
  SET_CURRENT_USER:'SET_CURRENT_USER',
  SET_LOGGED_USER:'SET_LOGGED_USER'
}
export const REGISTER = {
  PROCESS: 'SET_REGISTER_PROCESS',
  SUCCESS: 'SET_REGISTER_SUCCESS',
  FAILED: 'SET_REGISTER_FAILED',
  SETEMAIL: 'SET_EMAIL',
}
/****************
 COMPANY
 *****************/
export const COMPANY = {
    LOADING_GET: 'SET_COMPANY_LOADING_GET',
    SUCCESS_GET: 'SUCCESS_COMPANY_GET',
    FAILED_GET: 'FAILED_COMPANY_GET',
    LOADING_POST: 'SET_COMPANY_LOADING_POST',
    SUCCESS_POST: 'SUCCESS_COMPANY_POST',
    FAILED_POST: 'FAILED_COMPANY_POST',
}
/****************
    USERS
*****************/
export const USER_LIST = {
  LOADING: 'SET_USER_LIST_LOADING',
  LOADING_POST: 'SET_USER_LIST_LOADING_POST',
  IS_ERROR: 'SET_USER_LIST_IS_ERROR',
  SUCCESS: 'SUCCESS_USER_LIST',
  FAILED: 'FAILED_USER_LIST',
  DETAIL: 'DETAIL_USER_LIST',
  EDIT: 'EDIT_USER_LIST'
}

/****************
 DASHBOARD
 *****************/
export const DASHBOARD = {
  LOADING: 'SET_DASHBOARD_LOADING',
  SUCCESS: 'SET_DASHBOARD_SUCCESS',
  SUCCESS_NEWEST: 'SET_DASHBOARD_SUCCESS_NEWEST',
  FAILED: 'SET_DASHBOARD_FAILED',
  DETAIL: 'SET_DASHBOARD_DETAIL',
  POST_LOADING: 'SET_DASHBOARD_POST_LOADING'
}


/****************
 SITE SECTION
 *****************/
export const SITE = {
  LOADING: 'SET_SITE_LOADING',
  SUCCESS: 'SET_SITE_SUCCESS',
  SUCCESS_LIST: 'SET_SITE_SUCCESS_LIST',
  SUCCESS_FOLDER: 'SET_SITE_SUCCESS_FOLDER',
  SUCCESS_TABLES: 'SET_SITE_SUCCESS_TABLES',
  FAILED: 'SET_SITE_FAILED',
  DETAIL: 'SET_SITE_DETAIL',
  SUCCESS_CHECK: 'SET_SITE_SUCCESS_CHECK',
  TRIGGER_ECAPS: 'SET_TRIGGER_ECAPS',
  DOWNLOAD_TXT: 'SET_DOWNLOAD_TXT',
  TRIGGER_MOBILE_ECAPS: 'SET_TRIGGER_MOBILE_ECAPS'
}
/****************
 COIN TYPE
 *****************/
export const COIN_TYPE = {
    LOADING: 'SET_COIN_TYPE_LOADING',
    LOADING_POST: 'SET_COIN_TYPE_LOADING_POST',
    IS_ERROR: 'SET_COIN_TYPE_IS_ERROR',
    SUCCESS: 'SUCCESS_COIN_TYPE',
    FAILED: 'FAILED_COIN_TYPE',
    DETAIL: 'DETAIL_COIN_TYPE',
    EDIT: 'EDIT_COIN_TYPE'
}
/****************
 FAQ
 *****************/
export const FAQ = {
    LOADING: 'SET_FAQ_LOADING',
    LOADING_POST: 'SET_FAQ_LOADING_POST',
    IS_ERROR: 'SET_FAQ_IS_ERROR',
    SUCCESS: 'SUCCESS_FAQ',
    FAILED: 'FAILED_FAQ',
    DETAIL: 'DETAIL_FAQ',
    EDIT: 'EDIT_FAQ'
}